CREATE TABLE question (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_title VARCHAR(500) NOT NULL,
    option1 VARCHAR(255) NOT NULL,
    option2 VARCHAR(255) NOT NULL,
    option3 VARCHAR(255) NOT NULL,
    option4 VARCHAR(255) NOT NULL,
    right_answer VARCHAR(255) NOT NULL,
    difficultylevel VARCHAR(50) NOT NULL,
    category VARCHAR(100) NOT NULL
);

CREATE INDEX idx_question_category ON question (category);
