CREATE TABLE quiz (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE quiz_question_ids (
    quiz_id INTEGER NOT NULL REFERENCES quiz (id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL,
    position INTEGER NOT NULL,
    PRIMARY KEY (quiz_id, position)
);

CREATE INDEX idx_quiz_question_ids_quiz_id ON quiz_question_ids (quiz_id);
